services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SQL_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: CloudNativeInventory.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CloudNativeInventory;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=true
      - ExternalServices__VendorApiKey=${VENDOR_API_KEY}
    depends_on:
      - db

volumes:
  sqlserver_data: